- hosts: "{{ host_hook }}"
  gather_facts: false
  tasks:
    - command: vagrant up
      args:
        chdir: /kubespray
      environment:
        - K8SIZE: "{{ size }}"
      register: up
    - debug: msg=up